apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "zap-*"
    isDefault: false
    editable: false
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
